### ISSUE TITLE
Members with lower privileges and embed link with bot

### ISSUE THREAD

**Issue by ujjwal-kr** [hackarmour/discord-assistant#62]
![bug](https://media.discordapp.net/attachments/867789973717385256/868420665370374164/IMG_20210724_143916.jpg)
fix it lol

cc @itsmebirdie

**Comment by itsmebirdie** [comment]
Hi, thanks for pointing out the bug, we have already issued a fix in PR #61

**Comment by ujjwal-kr** [comment]
@itsmebirdie hi, thanks for not reading the code of #63 and saying that unknowingly.

**Comment by itsmebirdie** [comment]
issue has been fixed
deployment will be delayed
