### ISSUE TITLE
Bot considers messages to be edited after loading the embed

### ISSUE THREAD

**Issue by ujjwal-kr** [hackarmour/discord-assistant#68]
![IMG_20210805_191712](https://user-images.githubusercontent.com/38783809/128361237-1abf64df-c07f-4c25-8219-7b306740f513.jpg)

this creates unnecessary log content for the messages which has not even been updated.

**Comment by itsmebirdie** [comment]
Assigning @PhantomKnight287

**Comment by itsmebirdie** [comment]
Fix issued in #69
